import Image from 'next/image';
import Head from 'next/head';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next-Tailwind-Amazona</title>
        <meta name="description" content="Generated by next js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold">This is nothing</h1>
    </div>
  );
}
